### PR TITLE
Ske v1.79 cherry picks

### PR DESCRIPTION
**Pull request by nschad**
/kind enhancement

Minor dependency fun with the etcd-druid commit but nothing special.

### CODE REVIEW

**Review by robinschneider — APPROVED** [review]

**Comment by robinschneider** [comment]
@nschad Had to manually add the `approved` label.

**Comment by maboehm** [comment]
ahhhhhhh
This squashed!

**Comment by nschad** [comment]
> ahhhhhhh This squashed!

we should reconfigure prow then.

**Pull request merged**
