### PR TITLE
`v1.96.6` cherry-picks

### PR DESCRIPTION
**Pull request by Duciwuci**
How to categorize this PR?

/kind enhancement

What this PR does / why we need it:

Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:
Dropped Commits:
https://github.com/stackitcloud/gardener/pull/91/commits/9e33ab282fc74940dee96ea17d5c1345d84eea87

Part of https://github.com/stackitcloud/ske-base/issues/1598

### CODE REVIEW

**Comment by maboehm** [comment]
Please drop the "Revert" commits (and their original counterpart)

**Comment by Duciwuci** [comment]
> Please drop the "Revert" commits (and their original counterpart)

Done.

**Pull request merged**
