### PR TITLE
🧑🏻‍🌾 `v1.97` cherry-picks

### PR DESCRIPTION
**Pull request by ftl**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

The cherry-pick https://github.com/stackitcloud/gardener/pull/96/commits/4cd03daff2dee343f6d760f51dc97c5cb3ffab34 was dropped, it is part of gardener since v1.97.0

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by Duciwuci** [comment]
Mention also the drop of https://github.com/stackitcloud/gardener/pull/96/commits/4cd03daff2dee343f6d760f51dc97c5cb3ffab34

**Review by maboehm — CHANGES_REQUESTED** [review]
> The cherry-pick [a2967dba e9ac7fd64354664134bd7a6873206004](https://github.com/stackitcloud/gardener/pull/96/commits/a2967dbae9ac7fd64354664134bd7a6873206004) was dropped, it is part of gardener since v1.97.0

I dont think this points to the correct commit, since that is still included here

**Comment by maboehm** [comment]
/approve
will have to wait for `pull-gardener-unit` to complete

**Pull request merged**
