### PR TITLE
`v1.81.7`: update `etcd-druid`

### PR DESCRIPTION
**Pull request by Duciwuci**
/kind enhancement

### CODE REVIEW

**Comment by MichaelEischer** [comment]
The unit tests have failed:
```
>> make generate
make generate needs to be run:
 M example/seed-crds/10-crd-druid.gardener.cloud_etcds.yaml
```

**Comment by maboehm** [comment]
in the next version this should probably be combined with https://github.com/stackitcloud/gardener/pull/54/commits/d3a8d760246fd7ea4a74a2030dcc7edc97d06d48

**Comment by Duciwuci** [comment]
/unhold

we might be ready.

**Pull request merged**
