### PR TITLE
V1.77.6 ske cherry picks

### PR DESCRIPTION
**Pull request by maboehm**
dropped:
- 51432b28180ce82df95c26cb3f7a5f0339bbc48d
  - this is resolved in v1.77: https://github.com/gardener/gardener/pull/8281

I had to move the tests in 62eedc6ee32478278c0a20f35a0f45fcc73859be from `custom_resources_test.go` to `fluent_bit_test.go`

### CODE REVIEW

**Comment by maboehm** [comment]
`pull-gardener-e2e-kind` failure is expected as they dont work in our prow

**Comment by MichaelEischer** [comment]
Could `to v1.27: Ensure for every worker group that maximum workers is greater or equal to its number of zones` result in cluster upgrade problems ?

**Pull request merged**
