### PR TITLE
`v1.87` cherries

### PR DESCRIPTION
**Pull request by Duciwuci**
/kind enhancement

### CODE REVIEW

**Comment by Duciwuci** [comment]
We need to Upgrade `etcd-druid` before continuing cherry-picking

**Comment by Duciwuci** [comment]
https://github.com/stackitcloud/etcd-druid/releases/tag/v0.22.0-ske-1

New etcd-druid version released. Need to consider it at the next cherry-pick

**Comment by maboehm** [comment]
/lgtm

did not know that vendoring was dropped in 1.84

**Pull request merged**
